import SwiftUI
import CoreData
import Combine

class CuqavuHistoryViewModel: ObservableObject {
    @Published var axemobSessions: [AxemobSessionModel] = []
    @Published var ehonohSummaries: [CuqavuDailySummaryModel] = []
    @Published var degubaFilterType: EhonohSessionType?
    @Published var evubewFilterDays: Int = 30
    @Published var cuqavuSelectedSession: AxemobSessionModel?
    
    private let axemobLoadHistory: AxemobLoadHistoryUseCase
    
    init(context: NSManagedObjectContext = DegubaPersistenceController.shared.container.viewContext) {
        self.axemobLoadHistory = AxemobLoadHistoryUseCase(context: context)
    }
    
    func ehonohLoadData() {
        axemobSessions = axemobLoadHistory.evubewExecute(filterType: degubaFilterType, days: evubewFilterDays)
        ehonohSummaries = axemobLoadHistory.cuqavuLoadSummaries(days: evubewFilterDays)
    }
    
    func cuqavuApplyFilter(type: EhonohSessionType?) {
        degubaFilterType = type
        ehonohLoadData()
    }
    
    func degubaGroupedSessions() -> [Date: [AxemobSessionModel]] {
        let calendar = Calendar.current
        var grouped: [Date: [AxemobSessionModel]] = [:]
        
        for session in axemobSessions {
            let startOfDay = calendar.startOfDay(for: session.createdAt)
            if grouped[startOfDay] == nil {
                grouped[startOfDay] = []
            }
            grouped[startOfDay]?.append(session)
        }
        
        return grouped
    }
    
    func cuqavuGetTypeDistribution() -> [(type: EhonohSessionType, count: Int)] {
        var distribution: [EhonohSessionType: Int] = [:]
        
        for session in axemobSessions {
            distribution[session.type, default: 0] += 1
        }
        
        return EhonohSessionType.allCases.compactMap { type in
            if let count = distribution[type], count > 0 {
                return (type: type, count: count)
            }
            return nil
        }
    }
    
    // MARK: - Export Functions
    
    func ehonohShareStatistics(completion: @escaping ([Any]) -> Void) {
        let totalSessions = axemobSessions.count
        let totalMinutes = axemobSessions.reduce(0) { $0 + Int($1.durationMin) }
        let avgEnergy = axemobSessions.isEmpty ? 0.0 : Double(axemobSessions.reduce(0) { $0 + Int($1.energyLevel) }) / Double(totalSessions)
        let avgMood = axemobSessions.isEmpty ? 0.0 : Double(axemobSessions.reduce(0) { $0 + Int($1.mood) }) / Double(totalSessions)
        
        let distribution = cuqavuGetTypeDistribution()
        var distributionText = ""
        if distribution.isEmpty {
            distributionText = "No sessions yet\n"
        } else {
            for item in distribution {
                distributionText += "\(item.type.degubaTitle): \(item.count)\n"
            }
        }
        
        let statsText = """
        📊 Productivity Statistics
        
        Total Sessions: \(totalSessions)
        Total Time: \(totalMinutes) minutes
        Average Energy: \(String(format: "%.1f", avgEnergy))/10
        Average Mood: \(String(format: "%.1f", avgMood))/5
        
        Distribution by Type:
        \(distributionText)
        
        Generated by Bhydro Vigor
        """
        
        // Убеждаемся, что текст не пустой
        let finalText = statsText.trimmingCharacters(in: .whitespacesAndNewlines)
        if !finalText.isEmpty {
            completion([finalText])
        } else {
            completion(["No statistics available"])
        }
    }
    
    func evubewExportToCSV(completion: @escaping (URL?) -> Void) {
        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "yyyy-MM-dd HH:mm:ss"
        
        var csvContent = "Date,Type,Title,Duration (min),Energy Level,Mood,Start Time,End Time,Note\n"
        
        for session in axemobSessions {
            let date = dateFormatter.string(from: session.createdAt)
            let type = session.type.degubaTitle
            let title = session.title.replacingOccurrences(of: ",", with: ";")
            let duration = session.durationMin
            let energy = session.energyLevel
            let mood = session.mood
            let startTime = dateFormatter.string(from: session.startTime)
            let endTime = dateFormatter.string(from: session.endTime)
            let note = (session.note ?? "").replacingOccurrences(of: ",", with: ";").replacingOccurrences(of: "\n", with: " ")
            
            csvContent += "\(date),\(type),\(title),\(duration),\(energy),\(mood),\(startTime),\(endTime),\(note)\n"
        }
        
        saveToFile(content: csvContent, filename: "productivity_export.csv", completion: completion)
    }
    
    func degubaExportToJSON(completion: @escaping (URL?) -> Void) {
        let dateFormatter = ISO8601DateFormatter()
        
        let sessionsData = axemobSessions.map { session in
            [
                "id": session.id.uuidString,
                "createdAt": dateFormatter.string(from: session.createdAt),
                "type": session.type.degubaTitle,
                "typeRaw": session.type.rawValue,
                "title": session.title,
                "durationMin": session.durationMin,
                "energyLevel": session.energyLevel,
                "mood": session.mood,
                "startTime": dateFormatter.string(from: session.startTime),
                "endTime": dateFormatter.string(from: session.endTime),
                "note": session.note ?? "",
                "efficiencyScore": session.degubaEfficiencyScore
            ] as [String: Any]
        }
        
        let jsonData: [String: Any] = [
            "exportDate": dateFormatter.string(from: Date()),
            "totalSessions": axemobSessions.count,
            "sessions": sessionsData
        ]
        
        do {
            let jsonEncoder = JSONEncoder()
            jsonEncoder.outputFormatting = .prettyPrinted
            jsonEncoder.dateEncodingStrategy = .iso8601
            
            let jsonData = try JSONSerialization.data(withJSONObject: jsonData, options: .prettyPrinted)
            let jsonString = String(data: jsonData, encoding: .utf8) ?? ""
            
            saveToFile(content: jsonString, filename: "productivity_export.json", completion: completion)
        } catch {
            print("Error creating JSON: \(error)")
            completion(nil)
        }
    }
    
    private func saveToFile(content: String, filename: String, completion: @escaping (URL?) -> Void) {
        let tempDirectory = FileManager.default.temporaryDirectory
        let fileURL = tempDirectory.appendingPathComponent(filename)
        
        do {
            try content.write(to: fileURL, atomically: true, encoding: .utf8)
            completion(fileURL)
        } catch {
            print("Error saving file: \(error)")
            completion(nil)
        }
    }
}

